apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debug-pod-1
  name: debug-pod-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod-1
  template:
    metadata:
      labels:
        app: test-pod-1
    spec:
      containers:
        - image: docker.io/cherry22/debug-pod:v1.0.0
          imagePullPolicy: Always
          name: debug-pod