apiVersion: v1
kind: Service
metadata:
  name: public-grafana-svc
  namespace: default
  labels:
    app.kubernetes.io/name: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: grafana